name: finance27
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  share_plus:
  url_launcher:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.69.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/settings/
    - assets/category/
  fonts:
    - family: SFL
      fonts:
        - asset: assets/fonts/SFProText-Light.ttf
    - family: SFR
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf